---
Author: János Kövesdi
Version: 198 17-CNL 113 598, Rev. A
Date: 2013-09-06

---
= SMTP Protocol Modules for TTCN-3 Toolset with TITAN, User Guide
:author: János Kövesdi
:revnumber: 198 17-CNL 113 598, Rev. A
:revdate: 2013-09-06
:toc:

== About This Document

=== How to Read This Document

This is the User Guide for the SMTP protocol module. The SMTP protocol module is developed for the TTCN-3 Toolset with TITAN. This document should be read together with Function Specification <<_3, [3]>>.

=== Presumed Knowledge

To use this protocol module the knowledge of the TTCN-3 language <<_1, [1]>> is essential.

== System Requirements

Protocol modules are a set of TTCN-3 source code files that can be used as part of TTCN-3 test suites only. Hence, protocol modules alone do not put specific requirements on the system used. However in order to compile and execute a TTCN-3 test suite using the set of protocol modules the following system requirements must be satisfied:

* TITAN TTCN-3 Test Executor R7A (1.7.pl0) or higher installed. For installation guide see <<_2, [2]>>.

NOTE: This version of the protocol module is not compatible with TITAN releases earlier than R7A.

= Protocol Modules

== Overview

Protocol modules implement the messages structure of the related protocol in a formalized way, using the standard specification language TTCN-3. This allows defining of test data (templates) in the TTCN-3 language <<_1, [1]>> and correctly encoding/decoding messages when executing test suites using the Titan TTCN-3 test environment.

Protocol module is using Titan’s TEXT encoding attributes <<_2, [2]>> and hence is usable with the Titan test toolset only.

== Installation

The set of protocol modules can be used in developing TTCN-3 test suites using any text editor. However to make the work more efficient a TTCN-3-enabled text editor is recommended, for example `nedit`, `xemacs`. Since the SMTP protocol is used as a part of a TTCN-3 test suite, this requires TTCN-3 Test Executor be installed before the module can be compiled and executed together with other parts of the test suite. For more details on the installation of TTCN-3 Test Executor see the relevant section of <<_2, [2]>>.

== Configuration

None.

= Examples

The "demo" directory of the deliverable contains simple SMTP server which accepts any client connections, receive mails and after the connection if finished log the command sequence and the received mail.

The following files belong to the demo application:

* __SMTP_Demo.ttcn__ – Implements the demo SMTP server.

* __SMTP_Demo_functions.cc__ – Contains the implementation of `f_SMTP_getMsgLen` function.
+
The SMTP protocol is line oriented, so the received TCP stream should be buffered and the lines should be separated. The used test port, IPL4, is able to do it if the appropriate function is registered. The `f_SMTP_getMsgLen` tells the IPL4 test port, where the end of the line, so every receiving operation is will result one complete line.

* __SMTP_Demo.prj__ – Project file of the demo application.
+
Description of the demo SMTP server:
+
After the `SMTP_Server_demo` started, it opens the listening port and registers the `f_SMTP_getMsgLen` function.
+
The used host name and port number is taken from `tsp_local_host_name` and `tsp_local_port_number` module parameters.
+
After that, it starts to wait for incoming connection or incoming data on the live connection.
+
If the client connects to the SMTP server, it initializes the data structure and sends the welcome message.
+
If the client connection closed, the server logs the command/reply sequence, the raw and the decoded mail data.

If something is received from the client the demo analyzes it:

* In command mode:
+
In this mode the client can send commands to the server. The server decodes the received message and registers it in the command queue for logging.
+
According to what has been received, the server generates answer, switches to data mode or sends error reply.
+
If `DATA` command has been received, send the 354 reply and switch to data mode.
+
Quit command: Send 221 reply and logs the messages.
+
`HELO`, `RSET`, `NOOP`, `MAIL`, `RCPT` commands: Answered with OK.
+
Any other messages or the malformed messages answered with error reply.

* In data mode:
+
The server checks whether the end of the data is received or not
+
If the end of data sequence has been received (.CRLF) the demo switch back to command mode.
+
Otherwise the server removes the leading dot if necessary and appends the received line at the end of the mail data buffer.

= Terminology

No specific terminology is used.

= Abbreviations

SMTP:: Simple Mail Transfer Protocol

TTCN-3:: Testing and Test Control Notation version 3

=== References

[[_1]]
[1] ETSI ES 201 873-1 v.2.2.1 (02/2003) +
The Testing and Test Control Notation version 3. Part 1: Core Language

[[_2]]
[2] User Guide for TITAN TTCN-3 Test Executor

[[_3]]
[3] SMTP Protocol Modules for TTCN-3 Toolset with TITAN, Function Specification

[[_4]]
[4] https://tools.ietf.org/html/rfc821[RFC 821] +
Simple Mail Transfer Protocol

[[_5]]
[5] https://tools.ietf.org/html/rfc4861[RFC 822] +
Standard for the Format of ARPA Internet Text Messages

